"""
Django settings for filept project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hl8+pr@^28$20e-e-j+4^^gmrb$tdid#c!_(+tedo++z0g_&o^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userreviews',
    'reports',
    'django_filters',
    'bulk_update_or_create',
    'bootstrap3',
    'django_tables2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'filept.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'filept.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.TemporaryFileUploadHandler',]

CSV_HEADERS = {
     'ad_file':{
        'SAM Account Name': {'required':True},
        'Last Logon Time': {'required':True},
        'Full Name': {'required':False},
        'Email Address': {'required':False},
        'Manager': {'required':False},
        'Account Status': {'required':True},
        'When Created': {'required':False},
        'Password Status': {'required':True},
        'Department': {'required':False},
        'Mobile': {'required':False},
        'Company': {'required':False},
        'Password Expiry Date': {'required':False},
        'Days since password last set': {'required':False},
    },
     'user_review_file':{
        'Username': {'required':True},
        'Full Name': {'required':False},
        'Email Address': {'required':False},
        'Company': {'required':False},
        'Department': {'required':False},
        'Manager': {'required':False},
        'Date Created': {'required':False},
        'Last Logon': {'required':False},
        'Last Password Change': {'required':False},
        'Password Expiry Date': {'required':False},
        'Password Status': {'required':False},
        'Account Status': {'required':False},
        'Authentication Mechanism': {'required':True},
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_COLUMNS = {
    'username':'username',
    'fullname':'fullname',
    'email':'email',
    'mobile_phone':'mobile_phone',
    'date_last_logon':'date_last_logon',
}

USER_REVIEW_POLICY_SETTINGS = {
    'UNUSED_ACCOUNT_LOCKOUT_PERIOD':30,
    'PASSWORD_AGE':90
}