# Generated by Django 3.2.8 on 2021-10-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('manager', models.CharField(blank=True, max_length=20, null=True)),
                ('auth_type', models.CharField(blank=True, choices=[('AD', 'Active Directory'), ('LOCAL', 'Local'), ('u2020', 'Huawei EMS u2020')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_last_logon', models.DateTimeField(blank=True, null=True)),
                ('date_password_change', models.DateTimeField(blank=True, null=True)),
                ('password_status', models.CharField(blank=True, max_length=20, null=True)),
                ('account_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('username', 'auth_type')},
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('system_type', models.CharField(blank=True, choices=[('OS', 'Operating Sytem'), ('APP', 'Application'), ('DB', 'Database')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_logon', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userreviews.account')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userreviews.system')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='accounts',
            field=models.ManyToManyField(through='userreviews.SystemAccount', to='userreviews.Account'),
        ),
    ]
