# Generated by Django 3.2.8 on 2021-10-16 11:06

from django.db import migrations, models
import userreviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('userreviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='media/imports')),
                ('import_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
