# Generated by Django 3.2.8 on 2021-10-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreviews', '0002_importedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedFile',
        ),
    ]
