# Generated by Django 3.2.8 on 2021-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreviews', '0003_delete_importedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
