# Generated by Django 3.2.8 on 2021-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreviews', '0004_account_date_password_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
