# Generated by Django 3.2.8 on 2021-11-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreviews', '0005_account_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemaccount',
            name='date_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
